var searchData=
[
  ['d_20mission_20analysis_20in_20regards_20to_20power_0',['d) Mission analysis in regards to power',['../index.html#autotoc_md25',1,'']]],
  ['data_1',['data',['../index.html#autotoc_md32',1,'Battery and solar panel sizing data'],['../index.html#autotoc_md75',1,'Idle data']]],
  ['data_20field_2',['Transfer Frame Data Field',['../index.html#autotoc_md63',1,'']]],
  ['data_20field_20status_20tfdfs_3',['Transfer Frame Data Field Status (TFDFS)',['../index.html#autotoc_md55',1,'']]],
  ['data_20field_20usage_4',['Secondary header data field usage',['../index.html#autotoc_md62',1,'']]],
  ['data_20frame_20pdu_5',['Protocol data frame (PDU)',['../index.html#autotoc_md45',1,'']]],
  ['data_20limits_20and_20known_20issues_6',['Data limits and known issues',['../index.html#autotoc_md81',1,'']]],
  ['data_20link_20protocol_7',['Data Link Protocol',['../index.html#autotoc_md40',1,'CCSDS Telemetry(TM) Space Data Link Protocol'],['../index.html#autotoc_md41',1,'What is CCSDS Space Data Link Protocol']]],
  ['data_20rules_8',['Channel Data Rules',['../index.html#autotoc_md67',1,'']]],
  ['data_20transfer_20frames_9',['OID (Only Idle Data) Transfer Frames',['../index.html#autotoc_md70',1,'']]],
  ['data_20unit_20pdu_10',['CCSDS protocol data unit (PDU)',['../index.html#autotoc_md42',1,'']]],
  ['definition_11',['My Pin definition',['../index.html#autotoc_md18',1,'']]],
  ['descriptions_12',['Field descriptions',['../index.html#autotoc_md43',1,'']]],
  ['design_13',['5. Payload and Mission Design',['../index.html#autotoc_md33',1,'']]],
  ['design_20videos_20for_20visual_20consumers_14',['Design Videos for visual consumers',['../index.html#autotoc_md2',1,'']]],
  ['determination_20and_20control_15',['3. Attitude Determination and Control',['../index.html#autotoc_md19',1,'']]],
  ['different_20bus_20components_16',['a) Power consumption of different bus components',['../index.html#autotoc_md22',1,'']]],
  ['distribution_20schemes_17',['Power Distribution Schemes',['../index.html#autotoc_md28',1,'']]],
  ['docs_20images_20pc104_20dwg_20500_20gif_20alt_20shadow_20flight_20obc_20width_20400_20height_20400_18',['&lt;img src=&quot;./user-docs/images/pc104-dwg-500.gif&quot; alt=&quot;Shadow flight OBC&quot; width=&quot;400&quot; height=&quot;400&quot;/&gt;',['../index.html#autotoc_md16',1,'']]],
  ['documentation_19',['Web documentation',['../index.html#autotoc_md1',1,'']]],
  ['documents_20',['Related documents',['../index.html#autotoc_md82',1,'']]],
  ['dwg_20500_20gif_20alt_20shadow_20flight_20obc_20width_20400_20height_20400_21',['&lt;img src=&quot;./user-docs/images/pc104-dwg-500.gif&quot; alt=&quot;Shadow flight OBC&quot; width=&quot;400&quot; height=&quot;400&quot;/&gt;',['../index.html#autotoc_md16',1,'']]]
];
