var searchData=
[
  ['c_20energy_20storage_0',['c) Energy storage',['../index.html#autotoc_md26',1,'']]],
  ['ccsds_20protocol_20data_20unit_20pdu_1',['CCSDS protocol data unit (PDU)',['../index.html#autotoc_md44',1,'']]],
  ['ccsds_20space_20data_20link_20protocol_2',['What is CCSDS Space Data Link Protocol',['../index.html#autotoc_md43',1,'']]],
  ['ccsds_20telemetry_20tm_20space_20data_20link_20protocol_3',['CCSDS Telemetry(TM) Space Data Link Protocol',['../index.html#autotoc_md42',1,'']]],
  ['ccsds_20transfer_20frame_20header_20–_20virtual_20channel_20control_20flag_20and_20counters_4',['CCSDS Transfer Frame Header – Virtual Channel, Control Flag, and Counters',['../index.html#autotoc_md52',1,'']]],
  ['ccsds_20transfer_20frame_20secondary_20header_5',['CCSDS Transfer Frame Secondary Header',['../index.html#autotoc_md59',1,'']]],
  ['channel_20association_6',['Channel Association',['../index.html#autotoc_md62',1,'']]],
  ['channel_20control_20flag_20and_20counters_7',['CCSDS Transfer Frame Header – Virtual Channel, Control Flag, and Counters',['../index.html#autotoc_md52',1,'']]],
  ['channel_20data_20rules_8',['Channel Data Rules',['../index.html#autotoc_md69',1,'']]],
  ['channel_20frame_20count_20mcfc_9',['Master Channel Frame Count (MCFC)',['../index.html#autotoc_md55',1,'']]],
  ['channel_20frame_20count_20vcfc_10',['Virtual Channel Frame Count (VCFC)',['../index.html#autotoc_md56',1,'']]],
  ['channel_20identifier_20vcid_11',['Virtual Channel Identifier (VCID)',['../index.html#autotoc_md53',1,'']]],
  ['communication_20interface_12',['Payload communication interface',['../index.html#autotoc_md37',1,'']]],
  ['communication_20protocol_13',['Communication Protocol',['../index.html#autotoc_md41',1,'']]],
  ['communication_20protocol_20for_20sensors_14',['Communication protocol for sensors',['../index.html#autotoc_md15',1,'']]],
  ['components_15',['components',['../index.html#autotoc_md24',1,'a) Power consumption of different bus components'],['../index.html#autotoc_md7',1,'System components']]],
  ['components_20of_20the_20obc_16',['Components of the OBC',['../index.html#autotoc_md11',1,'']]],
  ['computer_17',['1. Onboard Computer',['../index.html#autotoc_md8',1,'']]],
  ['consumers_18',['Design Videos for visual consumers',['../index.html#autotoc_md4',1,'']]],
  ['consumption_20of_20different_20bus_20components_19',['a) Power consumption of different bus components',['../index.html#autotoc_md24',1,'']]],
  ['contents_20',['Contents',['../index.html#autotoc_md68',1,'Field Contents'],['../index.html#autotoc_md0',1,'Table of Contents']]],
  ['contribution_20and_20support_21',['Contribution and support',['../index.html#autotoc_md86',1,'']]],
  ['contributors_22',['Contributors',['../index.html#autotoc_md87',1,'']]],
  ['control_23',['3. Attitude Determination and Control',['../index.html#autotoc_md21',1,'']]],
  ['control_24',['Power supply control',['../index.html#autotoc_md31',1,'']]],
  ['control_20field_20fecf_25',['Frame Error Control Field (FECF)',['../index.html#autotoc_md78',1,'']]],
  ['control_20field_20flag_20ocf_20flag_26',['Operational Control Field Flag (OCF Flag)',['../index.html#autotoc_md54',1,'']]],
  ['control_20flag_20and_20counters_27',['CCSDS Transfer Frame Header – Virtual Channel, Control Flag, and Counters',['../index.html#autotoc_md52',1,'']]],
  ['conversion_28',['Conversion',['../index.html#autotoc_md29',1,'']]],
  ['count_20mcfc_29',['Master Channel Frame Count (MCFC)',['../index.html#autotoc_md55',1,'']]],
  ['count_20vcfc_30',['Virtual Channel Frame Count (VCFC)',['../index.html#autotoc_md56',1,'']]],
  ['counters_31',['CCSDS Transfer Frame Header – Virtual Channel, Control Flag, and Counters',['../index.html#autotoc_md52',1,'']]],
  ['cubesat_32',['Project Shadow Flight - A 1U Cubesat',['../index.html',1,'']]]
];
