var searchData=
[
  ['c_20energy_20storage_0',['c) Energy storage',['../index.html#autotoc_md24',1,'']]],
  ['ccsds_20protocol_20data_20unit_20pdu_1',['CCSDS protocol data unit (PDU)',['../index.html#autotoc_md42',1,'']]],
  ['ccsds_20space_20data_20link_20protocol_2',['What is CCSDS Space Data Link Protocol',['../index.html#autotoc_md41',1,'']]],
  ['ccsds_20telemetry_20tm_20space_20data_20link_20protocol_3',['CCSDS Telemetry(TM) Space Data Link Protocol',['../index.html#autotoc_md40',1,'']]],
  ['ccsds_20transfer_20frame_20header_20–_20virtual_20channel_20control_20flag_20and_20counters_4',['CCSDS Transfer Frame Header – Virtual Channel, Control Flag, and Counters',['../index.html#autotoc_md50',1,'']]],
  ['ccsds_20transfer_20frame_20secondary_20header_5',['CCSDS Transfer Frame Secondary Header',['../index.html#autotoc_md57',1,'']]],
  ['channel_20association_6',['Channel Association',['../index.html#autotoc_md60',1,'']]],
  ['channel_20control_20flag_20and_20counters_7',['CCSDS Transfer Frame Header – Virtual Channel, Control Flag, and Counters',['../index.html#autotoc_md50',1,'']]],
  ['channel_20data_20rules_8',['Channel Data Rules',['../index.html#autotoc_md67',1,'']]],
  ['channel_20frame_20count_20mcfc_9',['Master Channel Frame Count (MCFC)',['../index.html#autotoc_md53',1,'']]],
  ['channel_20frame_20count_20vcfc_10',['Virtual Channel Frame Count (VCFC)',['../index.html#autotoc_md54',1,'']]],
  ['channel_20identifier_20vcid_11',['Virtual Channel Identifier (VCID)',['../index.html#autotoc_md51',1,'']]],
  ['communication_20interface_12',['Payload communication interface',['../index.html#autotoc_md35',1,'']]],
  ['communication_20protocol_13',['Communication Protocol',['../index.html#autotoc_md39',1,'']]],
  ['communication_20protocol_20for_20sensors_14',['Communication protocol for sensors',['../index.html#autotoc_md13',1,'']]],
  ['components_15',['components',['../index.html#autotoc_md22',1,'a) Power consumption of different bus components'],['../index.html#autotoc_md5',1,'System components']]],
  ['components_20of_20the_20obc_16',['Components of the OBC',['../index.html#autotoc_md9',1,'']]],
  ['computer_17',['1. Onboard Computer',['../index.html#autotoc_md6',1,'']]],
  ['consumers_18',['Design Videos for visual consumers',['../index.html#autotoc_md2',1,'']]],
  ['consumption_20of_20different_20bus_20components_19',['a) Power consumption of different bus components',['../index.html#autotoc_md22',1,'']]],
  ['contents_20',['Field Contents',['../index.html#autotoc_md66',1,'']]],
  ['contribution_20and_20support_21',['Contribution and support',['../index.html#autotoc_md84',1,'']]],
  ['contributors_22',['Contributors',['../index.html#autotoc_md85',1,'']]],
  ['control_23',['3. Attitude Determination and Control',['../index.html#autotoc_md19',1,'']]],
  ['control_24',['Power supply control',['../index.html#autotoc_md29',1,'']]],
  ['control_20field_20fecf_25',['Frame Error Control Field (FECF)',['../index.html#autotoc_md76',1,'']]],
  ['control_20field_20flag_20ocf_20flag_26',['Operational Control Field Flag (OCF Flag)',['../index.html#autotoc_md52',1,'']]],
  ['control_20flag_20and_20counters_27',['CCSDS Transfer Frame Header – Virtual Channel, Control Flag, and Counters',['../index.html#autotoc_md50',1,'']]],
  ['conversion_28',['Conversion',['../index.html#autotoc_md27',1,'']]],
  ['count_20mcfc_29',['Master Channel Frame Count (MCFC)',['../index.html#autotoc_md53',1,'']]],
  ['count_20vcfc_30',['Virtual Channel Frame Count (VCFC)',['../index.html#autotoc_md54',1,'']]],
  ['counters_31',['CCSDS Transfer Frame Header – Virtual Channel, Control Flag, and Counters',['../index.html#autotoc_md50',1,'']]],
  ['cubesat_32',['Project Shadow Flight - A 1U amateur Cubesat',['../index.html',1,'']]]
];
