var searchData=
[
  ['schematics_20summary_0',['e) EPS Schematics summary',['../index.html#autotoc_md27',1,'']]],
  ['schemes_1',['Power Distribution Schemes',['../index.html#autotoc_md29',1,'']]],
  ['scid_2',['Spacecraft Identifier (SCID)',['../index.html#autotoc_md50',1,'']]],
  ['secondary_20header_3',['CCSDS Transfer Frame Secondary Header',['../index.html#autotoc_md58',1,'']]],
  ['secondary_20header_20data_20field_20usage_4',['Secondary header data field usage',['../index.html#autotoc_md63',1,'']]],
  ['sensor_20board_5',['2. Sensor Board',['../index.html#autotoc_md11',1,'']]],
  ['sensors_6',['Communication protocol for sensors',['../index.html#autotoc_md14',1,'']]],
  ['shadow_20flight_7',['Project-Shadow-Flight',['../index.html#autotoc_md0',1,'']]],
  ['shadow_20flight_20a_201u_20cubesat_8',['Project Shadow Flight - A 1U Cubesat',['../index.html',1,'']]],
  ['shadow_20flight_20obc_20width_20400_20height_20400_9',['&lt;img src=&quot;./user-docs/images/pc104-dwg-500.gif&quot; alt=&quot;Shadow flight OBC&quot; width=&quot;400&quot; height=&quot;400&quot;/&gt;',['../index.html#autotoc_md17',1,'']]],
  ['sizing_20data_10',['Battery and solar panel sizing data',['../index.html#autotoc_md33',1,'']]],
  ['solar_20panel_20sizing_20data_11',['Battery and solar panel sizing data',['../index.html#autotoc_md33',1,'']]],
  ['space_20data_20link_20protocol_12',['Space Data Link Protocol',['../index.html#autotoc_md41',1,'CCSDS Telemetry(TM) Space Data Link Protocol'],['../index.html#autotoc_md42',1,'What is CCSDS Space Data Link Protocol']]],
  ['spacecraft_20identifier_20scid_13',['Spacecraft Identifier (SCID)',['../index.html#autotoc_md50',1,'']]],
  ['src_20user_20docs_20images_20pc104_20dwg_20500_20gif_20alt_20shadow_20flight_20obc_20width_20400_20height_20400_14',['&lt;img src=&quot;./user-docs/images/pc104-dwg-500.gif&quot; alt=&quot;Shadow flight OBC&quot; width=&quot;400&quot; height=&quot;400&quot;/&gt;',['../index.html#autotoc_md17',1,'']]],
  ['statement_15',['Mission statement',['../index.html#autotoc_md5',1,'']]],
  ['station_16',['Interface with the ground station',['../index.html#autotoc_md81',1,'']]],
  ['status_20tfdfs_17',['Transfer Frame Data Field Status (TFDFS)',['../index.html#autotoc_md56',1,'']]],
  ['storage_18',['c) Energy storage',['../index.html#autotoc_md25',1,'']]],
  ['structure_19',['Structure',['../index.html#autotoc_md60',1,'']]],
  ['summary_20',['e) EPS Schematics summary',['../index.html#autotoc_md27',1,'']]],
  ['supply_20control_21',['Power supply control',['../index.html#autotoc_md30',1,'']]],
  ['support_22',['Contribution and support',['../index.html#autotoc_md85',1,'']]],
  ['system_20components_23',['System components',['../index.html#autotoc_md6',1,'']]],
  ['system_20eps_24',['4. Electrical Power System (EPS)',['../index.html#autotoc_md21',1,'']]],
  ['system_20requirements_25',['Payload system requirements',['../index.html#autotoc_md35',1,'']]]
];
