var searchData=
[
  ['schematics_20summary_0',['e) EPS Schematics summary',['../index.html#autotoc_md26',1,'']]],
  ['schemes_1',['Power Distribution Schemes',['../index.html#autotoc_md28',1,'']]],
  ['scid_2',['Spacecraft Identifier (SCID)',['../index.html#autotoc_md49',1,'']]],
  ['secondary_20header_3',['CCSDS Transfer Frame Secondary Header',['../index.html#autotoc_md57',1,'']]],
  ['secondary_20header_20data_20field_20usage_4',['Secondary header data field usage',['../index.html#autotoc_md62',1,'']]],
  ['sensor_20board_5',['2. Sensor Board',['../index.html#autotoc_md10',1,'']]],
  ['sensors_6',['Communication protocol for sensors',['../index.html#autotoc_md13',1,'']]],
  ['shadow_20flight_20a_201u_20amateur_20cubesat_7',['Project Shadow Flight - A 1U amateur Cubesat',['../index.html',1,'']]],
  ['shadow_20flight_20obc_20width_20400_20height_20400_8',['&lt;img src=&quot;./user-docs/images/pc104-dwg-500.gif&quot; alt=&quot;Shadow flight OBC&quot; width=&quot;400&quot; height=&quot;400&quot;/&gt;',['../index.html#autotoc_md16',1,'']]],
  ['sizing_20data_9',['Battery and solar panel sizing data',['../index.html#autotoc_md32',1,'']]],
  ['solar_20panel_20sizing_20data_10',['Battery and solar panel sizing data',['../index.html#autotoc_md32',1,'']]],
  ['space_20data_20link_20protocol_11',['Space Data Link Protocol',['../index.html#autotoc_md40',1,'CCSDS Telemetry(TM) Space Data Link Protocol'],['../index.html#autotoc_md41',1,'What is CCSDS Space Data Link Protocol']]],
  ['spacecraft_20identifier_20scid_12',['Spacecraft Identifier (SCID)',['../index.html#autotoc_md49',1,'']]],
  ['src_20user_20docs_20images_20pc104_20dwg_20500_20gif_20alt_20shadow_20flight_20obc_20width_20400_20height_20400_13',['&lt;img src=&quot;./user-docs/images/pc104-dwg-500.gif&quot; alt=&quot;Shadow flight OBC&quot; width=&quot;400&quot; height=&quot;400&quot;/&gt;',['../index.html#autotoc_md16',1,'']]],
  ['statement_14',['Mission statement',['../index.html#autotoc_md4',1,'']]],
  ['station_15',['Interface with the ground station',['../index.html#autotoc_md80',1,'']]],
  ['status_20tfdfs_16',['Transfer Frame Data Field Status (TFDFS)',['../index.html#autotoc_md55',1,'']]],
  ['storage_17',['c) Energy storage',['../index.html#autotoc_md24',1,'']]],
  ['structure_18',['Structure',['../index.html#autotoc_md59',1,'']]],
  ['summary_19',['e) EPS Schematics summary',['../index.html#autotoc_md26',1,'']]],
  ['supply_20control_20',['Power supply control',['../index.html#autotoc_md29',1,'']]],
  ['support_21',['Contribution and support',['../index.html#autotoc_md84',1,'']]],
  ['system_20components_22',['System components',['../index.html#autotoc_md5',1,'']]],
  ['system_20eps_23',['4. Electrical Power System (EPS)',['../index.html#autotoc_md20',1,'']]],
  ['system_20requirements_24',['Payload system requirements',['../index.html#autotoc_md34',1,'']]]
];
