var searchData=
[
  ['packet_20placement_0',['Packet Placement',['../index.html#autotoc_md70',1,'']]],
  ['panel_20sizing_20data_1',['Battery and solar panel sizing data',['../index.html#autotoc_md34',1,'']]],
  ['payload_20and_20mission_20design_2',['5. Payload and Mission Design',['../index.html#autotoc_md35',1,'']]],
  ['payload_20communication_20interface_3',['Payload communication interface',['../index.html#autotoc_md37',1,'']]],
  ['payload_20pcb_4',['Payload PCB',['../index.html#autotoc_md38',1,'']]],
  ['payload_20system_20requirements_5',['Payload system requirements',['../index.html#autotoc_md36',1,'']]],
  ['pc_20104_20isa_20bus_6',['The PC/104 ISA Bus',['../index.html#autotoc_md16',1,'']]],
  ['pc104_20dwg_20500_20gif_20alt_20shadow_20flight_20obc_20width_20400_20height_20400_7',['&lt;img src=&quot;./user-docs/images/pc104-dwg-500.gif&quot; alt=&quot;Shadow flight OBC&quot; width=&quot;400&quot; height=&quot;400&quot;/&gt;',['../index.html#autotoc_md18',1,'']]],
  ['pcb_8',['Payload PCB',['../index.html#autotoc_md38',1,'']]],
  ['pdu_9',['PDU',['../index.html#autotoc_md44',1,'CCSDS protocol data unit (PDU)'],['../index.html#autotoc_md47',1,'Protocol data frame (PDU)']]],
  ['pin_20definition_10',['My Pin definition',['../index.html#autotoc_md20',1,'']]],
  ['placement_11',['Packet Placement',['../index.html#autotoc_md70',1,'']]],
  ['power_12',['d) Mission analysis in regards to power',['../index.html#autotoc_md27',1,'']]],
  ['power_20consumption_20of_20different_20bus_20components_13',['a) Power consumption of different bus components',['../index.html#autotoc_md24',1,'']]],
  ['power_20distribution_20schemes_14',['Power Distribution Schemes',['../index.html#autotoc_md30',1,'']]],
  ['power_20generation_15',['b) Power generation',['../index.html#autotoc_md25',1,'']]],
  ['power_20supply_20control_16',['Power supply control',['../index.html#autotoc_md31',1,'']]],
  ['power_20system_20eps_17',['4. Electrical Power System (EPS)',['../index.html#autotoc_md22',1,'']]],
  ['primary_20header_18',['1. Primary header',['../index.html#autotoc_md49',1,'']]],
  ['procedure_19',['Encoding Procedure',['../index.html#autotoc_md81',1,'']]],
  ['project_20shadow_20flight_20',['Project-Shadow-Flight',['../index.html#autotoc_md1',1,'']]],
  ['project_20shadow_20flight_20a_201u_20cubesat_21',['Project Shadow Flight - A 1U Cubesat',['../index.html',1,'']]],
  ['protocol_22',['Protocol',['../index.html#autotoc_md42',1,'CCSDS Telemetry(TM) Space Data Link Protocol'],['../index.html#autotoc_md41',1,'Communication Protocol'],['../index.html#autotoc_md43',1,'What is CCSDS Space Data Link Protocol']]],
  ['protocol_20data_20frame_20pdu_23',['Protocol data frame (PDU)',['../index.html#autotoc_md47',1,'']]],
  ['protocol_20data_20unit_20pdu_24',['CCSDS protocol data unit (PDU)',['../index.html#autotoc_md44',1,'']]],
  ['protocol_20for_20sensors_25',['Communication protocol for sensors',['../index.html#autotoc_md15',1,'']]],
  ['purpose_26',['Purpose',['../index.html#autotoc_md58',1,'']]]
];
