var searchData=
[
  ['schematics_20summary_0',['e) EPS Schematics summary',['../index.html#autotoc_md26',1,'']]],
  ['schemes_1',['Power Distribution Schemes',['../index.html#autotoc_md28',1,'']]],
  ['scid_2',['Spacecraft Identifier (SCID)',['../index.html#autotoc_md49',1,'']]],
  ['secondary_20header_3',['CCSDS Transfer Frame Secondary Header',['../index.html#autotoc_md57',1,'']]],
  ['secondary_20header_20data_20field_20usage_4',['Secondary header data field usage',['../index.html#autotoc_md62',1,'']]],
  ['sensor_20board_5',['2. Sensor Board',['../index.html#autotoc_md10',1,'']]],
  ['sensors_6',['Communication protocol for sensors',['../index.html#autotoc_md13',1,'']]],
  ['shadow_20flight_20a_201u_20amateur_20cubesat_7',['Project Shadow Flight - A 1U amateur Cubesat',['../index.html',1,'']]],
  ['sizing_20data_8',['Battery and solar panel sizing data',['../index.html#autotoc_md32',1,'']]],
  ['solar_20panel_20sizing_20data_9',['Battery and solar panel sizing data',['../index.html#autotoc_md32',1,'']]],
  ['space_20data_20link_20protocol_10',['Space Data Link Protocol',['../index.html#autotoc_md40',1,'CCSDS Telemetry(TM) Space Data Link Protocol'],['../index.html#autotoc_md41',1,'What is CCSDS Space Data Link Protocol']]],
  ['spacecraft_20identifier_20scid_11',['Spacecraft Identifier (SCID)',['../index.html#autotoc_md49',1,'']]],
  ['statement_12',['Mission statement',['../index.html#autotoc_md4',1,'']]],
  ['station_13',['Interface with the ground station',['../index.html#autotoc_md80',1,'']]],
  ['status_20tfdfs_14',['Transfer Frame Data Field Status (TFDFS)',['../index.html#autotoc_md55',1,'']]],
  ['storage_15',['c) Energy storage',['../index.html#autotoc_md24',1,'']]],
  ['structure_16',['Structure',['../index.html#autotoc_md59',1,'']]],
  ['summary_17',['e) EPS Schematics summary',['../index.html#autotoc_md26',1,'']]],
  ['supply_20control_18',['Power supply control',['../index.html#autotoc_md29',1,'']]],
  ['support_19',['Contribution and support',['../index.html#autotoc_md84',1,'']]],
  ['system_20components_20',['System components',['../index.html#autotoc_md5',1,'']]],
  ['system_20eps_21',['4. Electrical Power System (EPS)',['../index.html#autotoc_md20',1,'']]],
  ['system_20requirements_22',['Payload system requirements',['../index.html#autotoc_md34',1,'']]]
];
