var searchData=
[
  ['payload_20and_20eps_20using_20standard_20digital_20protocols_20e_20g_20uart_20i2c_20spi_0',['3. The CubeSat shall support inter-board wired communication between the OBC, payload, and EPS using standard digital protocols (e.g., UART, I2C, SPI).',['../index.html#autotoc_md11',1,'']]],
  ['payload_20board_20via_20a_20standardized_20electrical_20connector_20to_20exchange_20power_20control_20and_20data_20signals_1',['7. The CubeSat shall interface with the payload board via a standardized electrical connector to exchange power, control, and data signals.',['../index.html#autotoc_md15',1,'']]],
  ['pc_20104_20bus_2',['PC-104 BUS',['../index.html#autotoc_md25',1,'']]],
  ['perform_20reliable_20data_20processing_20and_20control_20operations_20using_20an_20stm32f401ccu6_20microcontroller_3',['1. The CubeSat shall perform reliable data processing and control operations using an STM32F401CCU6 microcontroller.',['../index.html#autotoc_md9',1,'']]],
  ['post_20deployment_4',['6. The CubeSat shall utilize deployment and &quot;Remove Before Flight&quot; (RBF) switches to ensure safe handling and automatic activation post-deployment.',['../index.html#autotoc_md14',1,'']]],
  ['power_5',['d) Mission analysis in regards to power',['../index.html#autotoc_md32',1,'']]],
  ['power_20consumption_20of_20different_20bus_20components_6',['a) Power consumption of different bus components',['../index.html#autotoc_md29',1,'']]],
  ['power_20control_20and_20data_20signals_7',['7. The CubeSat shall interface with the payload board via a standardized electrical connector to exchange power, control, and data signals.',['../index.html#autotoc_md15',1,'']]],
  ['power_20cycles_8',['2. The CubeSat shall store mission-critical data and logs in non-volatile memory to prevent data loss during power cycles.',['../index.html#autotoc_md10',1,'']]],
  ['power_20distribution_20schemes_9',['Power Distribution Schemes',['../index.html#autotoc_md35',1,'']]],
  ['power_20drops_10',['9. The CubeSat shall implement a brown-out detection mechanism to safely handle unexpected power drops.',['../index.html#autotoc_md17',1,'']]],
  ['power_20generation_11',['b) Power generation',['../index.html#autotoc_md30',1,'']]],
  ['power_20supply_20control_12',['Power supply control',['../index.html#autotoc_md36',1,'']]],
  ['power_20system_20eps_13',['4. Electrical Power System (EPS)',['../index.html#autotoc_md27',1,'']]],
  ['power_20system_20using_20telemetry_20from_20the_20eps_14',['8. The CubeSat shall monitor voltage and current levels of its power system using telemetry from the EPS.',['../index.html#autotoc_md16',1,'']]],
  ['premature_20activation_20of_20systems_15',['11. The CubeSat shall include up to 3 inhibit switches in accordance with CubeSat deployment standards to prevent premature activation of systems.',['../index.html#autotoc_md19',1,'']]],
  ['prevent_20data_20loss_20during_20power_20cycles_16',['2. The CubeSat shall store mission-critical data and logs in non-volatile memory to prevent data loss during power cycles.',['../index.html#autotoc_md10',1,'']]],
  ['prevent_20premature_20activation_20of_20systems_17',['11. The CubeSat shall include up to 3 inhibit switches in accordance with CubeSat deployment standards to prevent premature activation of systems.',['../index.html#autotoc_md19',1,'']]],
  ['processing_20and_20control_20operations_20using_20an_20stm32f401ccu6_20microcontroller_18',['1. The CubeSat shall perform reliable data processing and control operations using an STM32F401CCU6 microcontroller.',['../index.html#autotoc_md9',1,'']]],
  ['programmable_20via_20an_20external_20programming_20debugging_20header_20accessible_20during_20integration_20and_20testing_19',['5. The CubeSat shall be programmable via an external programming/debugging header accessible during integration and testing.',['../index.html#autotoc_md13',1,'']]],
  ['programming_20debugging_20header_20accessible_20during_20integration_20and_20testing_20',['5. The CubeSat shall be programmable via an external programming/debugging header accessible during integration and testing.',['../index.html#autotoc_md13',1,'']]],
  ['project_20shadow_20flight_21',['Project-Shadow-Flight',['../index.html',1,'']]],
  ['protocol_20for_20sensors_22',['Communication protocol for sensors',['../index.html#autotoc_md24',1,'']]],
  ['protocols_20e_20g_20uart_20i2c_20spi_23',['3. The CubeSat shall support inter-board wired communication between the OBC, payload, and EPS using standard digital protocols (e.g., UART, I2C, SPI).',['../index.html#autotoc_md11',1,'']]]
];
