var searchData=
[
  ['safe_20handling_20and_20automatic_20activation_20post_20deployment_0',['6. The CubeSat shall utilize deployment and &quot;Remove Before Flight&quot; (RBF) switches to ensure safe handling and automatic activation post-deployment.',['../index.html#autotoc_md14',1,'']]],
  ['safely_20handle_20unexpected_20power_20drops_1',['9. The CubeSat shall implement a brown-out detection mechanism to safely handle unexpected power drops.',['../index.html#autotoc_md17',1,'']]],
  ['schematics_20summary_2',['e) EPS Schematics summary',['../index.html#autotoc_md33',1,'']]],
  ['schemes_3',['Power Distribution Schemes',['../index.html#autotoc_md35',1,'']]],
  ['sensor_20board_4',['2. Sensor Board',['../index.html#autotoc_md21',1,'']]],
  ['sensors_5',['Communication protocol for sensors',['../index.html#autotoc_md24',1,'']]],
  ['sensors_20used_6',['Sensors used',['../index.html#autotoc_md23',1,'']]],
  ['shadow_20flight_7',['Project-Shadow-Flight',['../index.html',1,'']]],
  ['shall_20be_20programmable_20via_20an_20external_20programming_20debugging_20header_20accessible_20during_20integration_20and_20testing_8',['5. The CubeSat shall be programmable via an external programming/debugging header accessible during integration and testing.',['../index.html#autotoc_md13',1,'']]],
  ['shall_20implement_20a_20brown_20out_20detection_20mechanism_20to_20safely_20handle_20unexpected_20power_20drops_9',['9. The CubeSat shall implement a brown-out detection mechanism to safely handle unexpected power drops.',['../index.html#autotoc_md17',1,'']]],
  ['shall_20include_20a_20hardware_20watchdog_20timer_20to_20recover_20from_20software_20faults_20or_20unresponsive_20states_10',['10. The CubeSat shall include a hardware watchdog timer to recover from software faults or unresponsive states.',['../index.html#autotoc_md18',1,'']]],
  ['shall_20include_20up_20to_203_20inhibit_20switches_20in_20accordance_20with_20cubesat_20deployment_20standards_20to_20prevent_20premature_20activation_20of_20systems_11',['11. The CubeSat shall include up to 3 inhibit switches in accordance with CubeSat deployment standards to prevent premature activation of systems.',['../index.html#autotoc_md19',1,'']]],
  ['shall_20indicate_20system_20and_20subsystem_20statuses_20using_20onboard_20status_20leds_12',['4. The CubeSat shall indicate system and subsystem statuses using onboard status LEDs.',['../index.html#autotoc_md12',1,'']]],
  ['shall_20interface_20with_20the_20payload_20board_20via_20a_20standardized_20electrical_20connector_20to_20exchange_20power_20control_20and_20data_20signals_13',['7. The CubeSat shall interface with the payload board via a standardized electrical connector to exchange power, control, and data signals.',['../index.html#autotoc_md15',1,'']]],
  ['shall_20monitor_20voltage_20and_20current_20levels_20of_20its_20power_20system_20using_20telemetry_20from_20the_20eps_14',['8. The CubeSat shall monitor voltage and current levels of its power system using telemetry from the EPS.',['../index.html#autotoc_md16',1,'']]],
  ['shall_20perform_20reliable_20data_20processing_20and_20control_20operations_20using_20an_20stm32f401ccu6_20microcontroller_15',['1. The CubeSat shall perform reliable data processing and control operations using an STM32F401CCU6 microcontroller.',['../index.html#autotoc_md9',1,'']]],
  ['shall_20store_20mission_20critical_20data_20and_20logs_20in_20non_20volatile_20memory_20to_20prevent_20data_20loss_20during_20power_20cycles_16',['2. The CubeSat shall store mission-critical data and logs in non-volatile memory to prevent data loss during power cycles.',['../index.html#autotoc_md10',1,'']]],
  ['shall_20support_20inter_20board_20wired_20communication_20between_20the_20obc_20payload_20and_20eps_20using_20standard_20digital_20protocols_20e_20g_20uart_20i2c_20spi_17',['3. The CubeSat shall support inter-board wired communication between the OBC, payload, and EPS using standard digital protocols (e.g., UART, I2C, SPI).',['../index.html#autotoc_md11',1,'']]],
  ['shall_20utilize_20deployment_20and_20remove_20before_20flight_20rbf_20switches_20to_20ensure_20safe_20handling_20and_20automatic_20activation_20post_20deployment_18',['6. The CubeSat shall utilize deployment and &quot;Remove Before Flight&quot; (RBF) switches to ensure safe handling and automatic activation post-deployment.',['../index.html#autotoc_md14',1,'']]],
  ['signals_19',['7. The CubeSat shall interface with the payload board via a standardized electrical connector to exchange power, control, and data signals.',['../index.html#autotoc_md15',1,'']]],
  ['software_20faults_20or_20unresponsive_20states_20',['10. The CubeSat shall include a hardware watchdog timer to recover from software faults or unresponsive states.',['../index.html#autotoc_md18',1,'']]],
  ['spi_21',['3. The CubeSat shall support inter-board wired communication between the OBC, payload, and EPS using standard digital protocols (e.g., UART, I2C, SPI).',['../index.html#autotoc_md11',1,'']]],
  ['standard_20digital_20protocols_20e_20g_20uart_20i2c_20spi_22',['3. The CubeSat shall support inter-board wired communication between the OBC, payload, and EPS using standard digital protocols (e.g., UART, I2C, SPI).',['../index.html#autotoc_md11',1,'']]],
  ['standardized_20electrical_20connector_20to_20exchange_20power_20control_20and_20data_20signals_23',['7. The CubeSat shall interface with the payload board via a standardized electrical connector to exchange power, control, and data signals.',['../index.html#autotoc_md15',1,'']]],
  ['standards_20to_20prevent_20premature_20activation_20of_20systems_24',['11. The CubeSat shall include up to 3 inhibit switches in accordance with CubeSat deployment standards to prevent premature activation of systems.',['../index.html#autotoc_md19',1,'']]],
  ['statement_25',['Mission statement',['../index.html#autotoc_md4',1,'']]],
  ['states_26',['10. The CubeSat shall include a hardware watchdog timer to recover from software faults or unresponsive states.',['../index.html#autotoc_md18',1,'']]],
  ['status_20leds_27',['4. The CubeSat shall indicate system and subsystem statuses using onboard status LEDs.',['../index.html#autotoc_md12',1,'']]],
  ['statuses_20using_20onboard_20status_20leds_28',['4. The CubeSat shall indicate system and subsystem statuses using onboard status LEDs.',['../index.html#autotoc_md12',1,'']]],
  ['stm32f401ccu6_20microcontroller_29',['1. The CubeSat shall perform reliable data processing and control operations using an STM32F401CCU6 microcontroller.',['../index.html#autotoc_md9',1,'']]],
  ['storage_30',['c) Energy storage',['../index.html#autotoc_md31',1,'']]],
  ['store_20mission_20critical_20data_20and_20logs_20in_20non_20volatile_20memory_20to_20prevent_20data_20loss_20during_20power_20cycles_31',['2. The CubeSat shall store mission-critical data and logs in non-volatile memory to prevent data loss during power cycles.',['../index.html#autotoc_md10',1,'']]],
  ['subsystem_20statuses_20using_20onboard_20status_20leds_32',['4. The CubeSat shall indicate system and subsystem statuses using onboard status LEDs.',['../index.html#autotoc_md12',1,'']]],
  ['summary_33',['e) EPS Schematics summary',['../index.html#autotoc_md33',1,'']]],
  ['supply_20control_34',['Power supply control',['../index.html#autotoc_md36',1,'']]],
  ['support_35',['Contribution and support',['../index.html#autotoc_md41',1,'']]],
  ['support_20inter_20board_20wired_20communication_20between_20the_20obc_20payload_20and_20eps_20using_20standard_20digital_20protocols_20e_20g_20uart_20i2c_20spi_36',['3. The CubeSat shall support inter-board wired communication between the OBC, payload, and EPS using standard digital protocols (e.g., UART, I2C, SPI).',['../index.html#autotoc_md11',1,'']]],
  ['switches_20in_20accordance_20with_20cubesat_20deployment_20standards_20to_20prevent_20premature_20activation_20of_20systems_37',['11. The CubeSat shall include up to 3 inhibit switches in accordance with CubeSat deployment standards to prevent premature activation of systems.',['../index.html#autotoc_md19',1,'']]],
  ['switches_20to_20ensure_20safe_20handling_20and_20automatic_20activation_20post_20deployment_38',['6. The CubeSat shall utilize deployment and &quot;Remove Before Flight&quot; (RBF) switches to ensure safe handling and automatic activation post-deployment.',['../index.html#autotoc_md14',1,'']]],
  ['system_20and_20subsystem_20statuses_20using_20onboard_20status_20leds_39',['4. The CubeSat shall indicate system and subsystem statuses using onboard status LEDs.',['../index.html#autotoc_md12',1,'']]],
  ['system_20components_40',['System components',['../index.html#autotoc_md5',1,'']]],
  ['system_20eps_41',['4. Electrical Power System (EPS)',['../index.html#autotoc_md27',1,'']]],
  ['system_20using_20telemetry_20from_20the_20eps_42',['8. The CubeSat shall monitor voltage and current levels of its power system using telemetry from the EPS.',['../index.html#autotoc_md16',1,'']]],
  ['systems_43',['11. The CubeSat shall include up to 3 inhibit switches in accordance with CubeSat deployment standards to prevent premature activation of systems.',['../index.html#autotoc_md19',1,'']]]
];
